### ISSUE TITLE
Deleting note is not working properly

### ISSUE THREAD

**Issue by prosperian** [TheCodeMonks/Notzz-App#160]
Hi
After deleting a note it will still remains on the screen.

https://user-images.githubusercontent.com/25820674/115970765-d5a58900-a559-11eb-8a5b-b043c02e5610.mp4

**Comment by Spikeysanju** [comment]
Hi @prosperian  Thanks for raising this bug. I've fixed this issue in the latest PR. Kindly please check it out!. Have a great day!

## Working preview 👇 
https://user-images.githubusercontent.com/23400022/116005220-9c395000-a623-11eb-80dc-779af8000009.mp4
