### ISSUE TITLE
This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 4.2 or newer.

### ISSUE THREAD

**Issue by MaximVod** [TheCodeMonks/Notzz-App#46]
Try to start your app in AS
and see:
This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 4.2 or newer.

**Comment by Spikeysanju** [comment]
![Screenshot 2020-11-16 at 7 51 28 PM](https://user-images.githubusercontent.com/23400022/99264711-d4ec2680-2846-11eb-8f58-acd3ce5c20c1.png)

@MaximVod
