### ISSUE TITLE
To fix the text out of screen

### ISSUE THREAD

**Issue by zinark-martin** [TheCodeMonks/Notzz-App#5]
item_post_notes.xml  -> TextView -> use android:layout_width="0dp" or "match_parent" instead of "wrap_content"
This will fix the text of each item out of screen promblem in NotesFragment

**Comment by zinark-martin** [comment]
When navigating to a destination, use "app: popUpTo" to set the target fragment, will clean the return stack between, so that when the user go to the notesFragment after save the note and press the back button,  he/she won't go back to the previous detailsFragment again

**Comment by Spikeysanju** [comment]
@zinark-martin  Sure will fix that. Thanks for taking time to sorting out this

**Comment by zinark-martin** [comment]
> @zinark-martin Sure will fix that. Thanks for taking time to sorting out this
😉👍

**Comment by zinark-martin** [comment]
😉👍

**Comment by Spikeysanju** [comment]
I have fixed this issue. Thanks for taking the time to sort out this 👍
