### ISSUE TITLE
Use "PopUpTo" to clean the stack between

### ISSUE THREAD

**Issue by zinark-martin** [TheCodeMonks/Notzz-App#6]
When navigating to a destination, use "app: popUpTo" to set the target fragment, will clean the return stack between, so that when the user go to the notesFragment after save the note and press the back button, he/she won't go back to the previous detailsFragment again
https://developer.android.com/guide/navigation/navigation-navigate

**Comment by Spikeysanju** [comment]
Thanks for pointing it out. Issue fixed in the latest build 👍
